/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_pillon_baptiste_ffmpeg_Processor */

#ifndef _Included_co_pillon_baptiste_ffmpeg_Processor
#define _Included_co_pillon_baptiste_ffmpeg_Processor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_pillon_baptiste_ffmpeg_Processor
 * Method:    run
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_co_pillon_baptiste_ffmpeg_Processor_run
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif